# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
