# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_wine_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
        migrations.AddField(
            model_name='wine',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
